import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createRequire } from 'node:module';
import test from 'node:test';
import { DataSource } from 'typeorm';

const require = createRequire(import.meta.url);
const {
  AddEmployeeRole1790830000000,
} = require('../dist/database/migrations/1790830000000-add-employee-role.js');

const testDatabaseUrl = process.env.TEST_DATABASE_URL;

test('employee role migration backfills legacy admins and is reversible', async (context) => {
  if (!testDatabaseUrl) {
    context.skip(
      'Set TEST_DATABASE_URL to an isolated PostgreSQL database ending in _test.',
    );
    return;
  }

  let databaseName;
  try {
    databaseName = decodeURIComponent(
      new URL(testDatabaseUrl).pathname.slice(1),
    );
  } catch {
    assert.fail('TEST_DATABASE_URL must be a valid PostgreSQL connection URL.');
  }
  assert.ok(
    databaseName.toLowerCase().endsWith('_test'),
    'Refusing to run migration test against a database without the _test suffix.',
  );

  const dataSource = new DataSource({
    type: 'postgres',
    url: testDatabaseUrl,
    entities: [],
    migrations: [],
    synchronize: false,
    logging: false,
  });
  await dataSource.initialize();

  const runner = dataSource.createQueryRunner();
  const schemaName = `employee_role_migration_${process.pid}_${randomBytes(4).toString('hex')}`;
  let schemaCreated = false;

  try {
    await runner.connect();
    await runner.query(`CREATE SCHEMA "${schemaName}"`);
    schemaCreated = true;
    await runner.query(`SET search_path TO "${schemaName}"`);
    await runner.query(`
      CREATE TABLE "employee" (
        "employee_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" varchar(120) NOT NULL,
        "email" varchar(254) NOT NULL,
        "phone" varchar(30),
        "password_hash" varchar(255) NOT NULL,
        "position" varchar(80) NOT NULL,
        "status" varchar(30) NOT NULL DEFAULT 'active'
      )
    `);
    await runner.query(
      `INSERT INTO "employee" ("name", "email", "password_hash", "position") VALUES
       ('Legacy Admin', 'admin@example.test', 'hash', ' Admin '),
       ('Legacy Staff', 'staff@example.test', 'hash', 'Sales Manager')`,
    );

    const migration = new AddEmployeeRole1790830000000();
    await migration.up(runner);

    const migratedEmployees = await runner.query(
      'SELECT "email", "role" FROM "employee" ORDER BY "email"',
    );
    assert.deepEqual(migratedEmployees, [
      { email: 'admin@example.test', role: 'admin' },
      { email: 'staff@example.test', role: 'unassigned' },
    ]);

    const roleIndex = await runner.query(
      `SELECT 1 FROM pg_indexes WHERE schemaname = $1 AND indexname = 'IDX_employee_role_status'`,
      [schemaName],
    );
    assert.equal(
      roleIndex.length,
      1,
      'Migration should add the role/status index.',
    );

    await assert.rejects(
      runner.query(
        `UPDATE "employee" SET "role" = 'unknown' WHERE "email" = 'staff@example.test'`,
      ),
      (error) => error?.code === '23514',
      'The role check constraint must reject unsupported role values.',
    );

    await migration.down(runner);
    const roleColumn = await runner.query(
      `
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = $1 AND table_name = 'employee' AND column_name = 'role'
    `,
      [schemaName],
    );
    assert.deepEqual(
      roleColumn,
      [],
      'Down migration should remove the role column.',
    );
  } finally {
    if (schemaCreated) {
      await runner.query('SET search_path TO public');
      await runner.query(`DROP SCHEMA "${schemaName}" CASCADE`);
    }
    await runner.release();
    await dataSource.destroy();
  }
});
