import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createRequire } from 'node:module';
import test from 'node:test';
import { DataSource } from 'typeorm';

const require = createRequire(import.meta.url);
const { ConsolidateEmployeeRoles1790840000000 } = require('../dist/database/migrations/1790840000000-consolidate-employee-roles.js');
const testDatabaseUrl = process.env.TEST_DATABASE_URL;

test('employee role consolidation maps roles and rolls back conservatively', async (context) => {
  if (!testDatabaseUrl) {
    context.skip('Set TEST_DATABASE_URL to an isolated PostgreSQL database ending in _test.');
    return;
  }
  let databaseName;
  try { databaseName = decodeURIComponent(new URL(testDatabaseUrl).pathname.slice(1)); }
  catch { assert.fail('TEST_DATABASE_URL must be a valid PostgreSQL connection URL.'); }
  assert.ok(databaseName.toLowerCase().endsWith('_test'), 'Refusing to run migration test without the _test suffix.');

  const dataSource = new DataSource({ type: 'postgres', url: testDatabaseUrl, entities: [], migrations: [], synchronize: false, logging: false });
  await dataSource.initialize();
  const runner = dataSource.createQueryRunner();
  const schemaName = `employee_role_consolidation_${process.pid}_${randomBytes(4).toString('hex')}`;
  let schemaCreated = false;
  try {
    await runner.connect();
    await runner.query(`CREATE SCHEMA "${schemaName}"`);
    schemaCreated = true;
    await runner.query(`SET search_path TO "${schemaName}"`);
    await runner.query(`CREATE TABLE "employee" (
      "employee_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar(120) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(30),
      "password_hash" varchar(255) NOT NULL, "position" varchar(80) NOT NULL,
      "status" varchar(30) NOT NULL DEFAULT 'active', "role" varchar(30) NOT NULL DEFAULT 'unassigned',
      CONSTRAINT "CHK_employee_role" CHECK ("role" IN ('admin', 'catalog_manager', 'promotion_manager', 'order_staff', 'purchasing_staff', 'unassigned'))
    )`);
    await runner.query('CREATE INDEX "IDX_employee_role_status" ON "employee" ("role", "status")');
    await runner.query(`INSERT INTO "employee" ("name", "email", "password_hash", "position", "status", "role") VALUES
      ('Admin', 'admin@example.test', 'hash', 'Admin', 'active', 'admin'),
      ('Catalog', 'catalog@example.test', 'hash', 'Catalog', 'active', 'catalog_manager'),
      ('Promotion', 'promotion@example.test', 'hash', 'Promotion', 'active', 'promotion_manager'),
      ('Order', 'order@example.test', 'hash', 'Order', 'inactive', 'order_staff'),
      ('Purchasing', 'purchasing@example.test', 'hash', 'Purchasing', 'active', 'purchasing_staff'),
      ('Unassigned active', 'unassigned-active@example.test', 'hash', 'Staff', 'active', 'unassigned'),
      ('Unassigned inactive', 'unassigned-inactive@example.test', 'hash', 'Staff', 'inactive', 'unassigned')`);

    const migration = new ConsolidateEmployeeRoles1790840000000();
    await migration.up(runner);
    const migrated = await runner.query('SELECT "email", "role", "status" FROM "employee" ORDER BY "email"');
    assert.deepEqual(migrated, [
      { email: 'admin@example.test', role: 'admin', status: 'active' },
      { email: 'catalog@example.test', role: 'manager', status: 'active' },
      { email: 'order@example.test', role: 'manager', status: 'inactive' },
      { email: 'promotion@example.test', role: 'manager', status: 'active' },
      { email: 'purchasing@example.test', role: 'manager', status: 'active' },
      { email: 'unassigned-active@example.test', role: 'manager', status: 'inactive' },
      { email: 'unassigned-inactive@example.test', role: 'manager', status: 'inactive' },
    ]);
    const defaults = await runner.query(`SELECT column_default FROM information_schema.columns WHERE table_schema = $1 AND table_name = 'employee' AND column_name = 'role'`, [schemaName]);
    assert.equal(defaults[0]?.column_default, "'manager'::character varying");
    const roleIndex = await runner.query(`SELECT 1 FROM pg_indexes WHERE schemaname = $1 AND indexname = 'IDX_employee_role_status'`, [schemaName]);
    assert.equal(roleIndex.length, 1, 'Role/status index must be preserved.');
    await assert.rejects(runner.query(`UPDATE "employee" SET "role" = 'unknown' WHERE "email" = 'admin@example.test'`), (error) => error?.code === '23514');

    await migration.down(runner);
    const rolledBack = await runner.query('SELECT "email", "role", "status" FROM "employee" ORDER BY "email"');
    assert.deepEqual(rolledBack, [
      { email: 'admin@example.test', role: 'admin', status: 'active' },
      { email: 'catalog@example.test', role: 'unassigned', status: 'active' },
      { email: 'order@example.test', role: 'unassigned', status: 'inactive' },
      { email: 'promotion@example.test', role: 'unassigned', status: 'active' },
      { email: 'purchasing@example.test', role: 'unassigned', status: 'active' },
      { email: 'unassigned-active@example.test', role: 'unassigned', status: 'inactive' },
      { email: 'unassigned-inactive@example.test', role: 'unassigned', status: 'inactive' },
    ]);
    const rollbackDefaults = await runner.query(`SELECT column_default FROM information_schema.columns WHERE table_schema = $1 AND table_name = 'employee' AND column_name = 'role'`, [schemaName]);
    assert.equal(rollbackDefaults[0]?.column_default, "'unassigned'::character varying");
    await assert.rejects(runner.query(`UPDATE "employee" SET "role" = 'manager' WHERE "email" = 'admin@example.test'`), (error) => error?.code === '23514');
  } finally {
    if (schemaCreated) {
      await runner.query('SET search_path TO public');
      await runner.query(`DROP SCHEMA "${schemaName}" CASCADE`);
    }
    await runner.release();
    await dataSource.destroy();
  }
});
