import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { createRequire } from 'node:module';
import test from 'node:test';
import { DataSource } from 'typeorm';

const require = createRequire(import.meta.url);
const {
  CreateProductImages1790850000000,
} = require('../dist/database/migrations/1790850000000-create-product-images.js');
const {
  AddProductImageHttpsCheck1790860000000,
} = require('../dist/database/migrations/1790860000000-add-product-image-https-check.js');
const { Category } = require('../dist/catalog/entities/category.entity.js');
const { Product } = require('../dist/catalog/entities/product.entity.js');
const {
  ProductImage,
} = require('../dist/catalog/entities/product-image.entity.js');
const {
  ProductVariant,
} = require('../dist/catalog/entities/product-variant.entity.js');
const testDatabaseUrl = process.env.TEST_DATABASE_URL;

function requireTestDatabaseName(url) {
  let databaseName;
  try {
    databaseName = decodeURIComponent(new URL(url).pathname.slice(1));
  } catch {
    assert.fail('TEST_DATABASE_URL must be a valid PostgreSQL connection URL.');
  }
  assert.ok(
    databaseName.toLowerCase().endsWith('_test'),
    'Refusing to run migration test against a database without the _test suffix.',
  );
}

async function readProductImageConstraints(runner) {
  return runner.query(
    `SELECT conname, pg_get_constraintdef(oid) AS definition
     FROM pg_constraint
     WHERE conrelid = 'product_image'::regclass
     ORDER BY conname`,
  );
}

test('product image migration history supports clean and legacy schemas', async (context) => {
  if (!testDatabaseUrl) {
    context.skip(
      'Set TEST_DATABASE_URL to an isolated PostgreSQL database ending in _test.',
    );
    return;
  }
  requireTestDatabaseName(testDatabaseUrl);

  const dataSource = new DataSource({
    type: 'postgres',
    url: testDatabaseUrl,
    entities: [Category, Product, ProductVariant, ProductImage],
    migrations: [],
    synchronize: false,
    logging: false,
  });
  await dataSource.initialize();

  const imageMetadata = dataSource.getMetadata(ProductImage);
  const primaryIndex = imageMetadata.indices.find(
    (index) => index.name === 'UQ_product_image_primary',
  );
  assert.ok(
    primaryIndex,
    'Entity metadata should include the persisted primary-image index.',
  );
  assert.equal(primaryIndex.isUnique, true);
  assert.equal(primaryIndex.where, '"is_primary" = true');

  const runner = dataSource.createQueryRunner();
  const schemaSuffix = `${process.pid}_${randomBytes(4).toString('hex')}`;
  const freshSchema = `product_image_fresh_${schemaSuffix}`;
  const legacySchema = `product_image_legacy_${schemaSuffix}`;
  const createdSchemas = [];
  const baseMigration = new CreateProductImages1790850000000();
  const httpsMigration = new AddProductImageHttpsCheck1790860000000();
  assert.equal(baseMigration.name, 'CreateProductImages1790850000000');
  assert.equal(httpsMigration.name, 'AddProductImageHttpsCheck1790860000000');

  try {
    await runner.connect();
    for (const schema of [freshSchema, legacySchema]) {
      await runner.query(`CREATE SCHEMA "${schema}"`);
      createdSchemas.push(schema);
    }

    // A fresh install applies the base table migration and then the additive
    // HTTPS constraint migration.
    await runner.query(`SET search_path TO "${freshSchema}"`);
    await runner.query(`
      CREATE TABLE "product" (
        "product_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
      )
    `);
    await baseMigration.up(runner);

    let constraints = await readProductImageConstraints(runner);
    assert.ok(
      !constraints.some(
        (constraint) => constraint.conname === 'CHK_product_image_https',
      ),
      'The historical base migration should match the already-applied legacy schema without the HTTPS check.',
    );
    await httpsMigration.up(runner);

    const columns = await runner.query(
      `SELECT column_name, character_maximum_length
       FROM information_schema.columns
       WHERE table_schema = $1 AND table_name = 'product_image'
       ORDER BY ordinal_position`,
      [freshSchema],
    );
    assert.deepEqual(
      columns.map((column) => column.column_name),
      [
        'product_image_id',
        'product_id',
        'image_url',
        'alt_text',
        'sort_order',
        'is_primary',
      ],
    );
    assert.equal(
      columns.find((column) => column.column_name === 'image_url')
        ?.character_maximum_length,
      2048,
    );
    assert.equal(
      columns.find((column) => column.column_name === 'alt_text')
        ?.character_maximum_length,
      200,
    );

    constraints = await readProductImageConstraints(runner);
    assert.ok(
      constraints.some(
        (constraint) => constraint.conname === 'CHK_product_image_https',
      ),
    );
    assert.ok(
      constraints.some(
        (constraint) =>
          constraint.conname === 'CHK_product_image_sort_order_nonnegative',
      ),
    );
    const foreignKey = constraints.find(
      (constraint) => constraint.conname === 'FK_product_image_product',
    );
    assert.ok(foreignKey);
    assert.match(foreignKey.definition, /ON DELETE CASCADE/i);
    assert.match(
      constraints.find(
        (constraint) => constraint.conname === 'CHK_product_image_https',
      ).definition,
      /https/i,
    );

    const indexes = await runner.query(
      `SELECT indexname, indexdef
       FROM pg_indexes
       WHERE schemaname = $1 AND tablename = 'product_image'`,
      [freshSchema],
    );
    const primaryIndex = indexes.find(
      (index) => index.indexname === 'UQ_product_image_primary',
    );
    assert.ok(
      primaryIndex,
      'Migration should add the historical partial unique primary-image index.',
    );
    assert.match(primaryIndex.indexdef, /WHERE \(is_primary = true\)/i);
    assert.ok(
      indexes.some(
        (index) => index.indexname === 'IDX_product_image_product_sort',
      ),
    );

    const productRows = await runner.query(
      'INSERT INTO "product" DEFAULT VALUES RETURNING "product_id"',
    );
    const productId = productRows[0].product_id;
    await runner.query(
      `INSERT INTO "product_image" ("product_id", "image_url", "is_primary") VALUES
       ($1, 'https://example.test/one.jpg', true),
       ($1, 'https://example.test/two.jpg', false)`,
      [productId],
    );
    await assert.rejects(
      runner.query(
        `INSERT INTO "product_image" ("product_id", "image_url", "is_primary")
         VALUES ($1, 'https://example.test/another-primary.jpg', true)`,
        [productId],
      ),
      (error) => error?.code === '23505',
      'The partial unique index must reject multiple primary images per product.',
    );
    await assert.rejects(
      runner.query(
        `INSERT INTO "product_image" ("product_id", "image_url")
         VALUES ($1, 'http://example.test/insecure.jpg')`,
        [productId],
      ),
      (error) => error?.code === '23514',
      'The additive HTTPS check must reject non-HTTPS image URLs.',
    );
    await assert.rejects(
      runner.query(
        `INSERT INTO "product_image" ("product_id", "image_url", "sort_order")
         VALUES ($1, 'https://example.test/negative.jpg', -1)`,
        [productId],
      ),
      (error) => error?.code === '23514',
      'The sort-order check must reject negative values.',
    );

    await runner.query('DELETE FROM "product" WHERE "product_id" = $1', [
      productId,
    ]);
    const remainingImages = await runner.query(
      'SELECT * FROM "product_image" WHERE "product_id" = $1',
      [productId],
    );
    assert.deepEqual(
      remainingImages,
      [],
      'Deleting a product should cascade to its images.',
    );

    await httpsMigration.down(runner);
    await baseMigration.down(runner);
    const freshTable = await runner.query(
      `SELECT 1 FROM information_schema.tables
       WHERE table_schema = $1 AND table_name = 'product_image'`,
      [freshSchema],
    );
    assert.deepEqual(
      freshTable,
      [],
      'Rolling back both fresh-install migrations should remove product_image.',
    );

    // An existing database has already applied the base migration. Apply only
    // the new migration, then prove its down step leaves the legacy table intact.
    await runner.query(`SET search_path TO "${legacySchema}"`);
    await runner.query(`
      CREATE TABLE "product" (
        "product_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
      )
    `);
    await baseMigration.up(runner);
    constraints = await readProductImageConstraints(runner);
    assert.ok(
      !constraints.some(
        (constraint) => constraint.conname === 'CHK_product_image_https',
      ),
      'Legacy table fixture should begin without the HTTPS constraint.',
    );
    const legacyProductRows = await runner.query(
      'INSERT INTO "product" DEFAULT VALUES RETURNING "product_id"',
    );
    const legacyProductId = legacyProductRows[0].product_id;
    await httpsMigration.up(runner);
    await assert.rejects(
      runner.query(
        `INSERT INTO "product_image" ("product_id", "image_url")
         VALUES ($1, 'http://example.test/insecure.jpg')`,
        [legacyProductId],
      ),
      (error) => error?.code === '23514',
      'The additive migration must enforce HTTPS on an existing legacy table.',
    );
    await httpsMigration.down(runner);
    constraints = await readProductImageConstraints(runner);
    assert.ok(
      !constraints.some(
        (constraint) => constraint.conname === 'CHK_product_image_https',
      ),
      'Rolling back the additive migration should remove only its HTTPS constraint.',
    );
    const legacyTable = await runner.query(
      `SELECT 1 FROM information_schema.tables
       WHERE table_schema = $1 AND table_name = 'product_image'`,
      [legacySchema],
    );
    assert.equal(
      legacyTable.length,
      1,
      'The additive migration down step must preserve the legacy table.',
    );
    await runner.query(
      `INSERT INTO "product_image" ("product_id", "image_url")
       VALUES ($1, 'http://example.test/legacy.jpg')`,
      [legacyProductId],
    );
    await baseMigration.down(runner);
  } finally {
    if (createdSchemas.length) {
      await runner.query('SET search_path TO public');
      for (const schema of createdSchemas) {
        await runner.query(`DROP SCHEMA "${schema}" CASCADE`);
      }
    }
    await runner.release();
    await dataSource.destroy();
  }
});
