/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#3f465c",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "destructive-soft": "#FEE2E2",
        "on-secondary-fixed": "#131b2e",
        "canvas": "#F8FAFC",
        "tertiary": "#005338",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "info-soft": "#E0F2FE",
        "on-tertiary-fixed": "#002113",
        "text-muted": "#64748B",
        "tertiary-fixed": "#6ffbbe",
        "inverse-primary": "#c3c0ff",
        "on-secondary": "#ffffff",
        "primary-container": "#4f46e5",
        "inverse-on-surface": "#eaf1ff",
        "surface-dim": "#cbdbf5",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#67f4b7",
        "error": "#ba1a1a",
        "on-primary-fixed": "#0f0069",
        "inverse-surface": "#213145",
        "surface-container": "#e5eeff",
        "background": "#f8f9ff",
        "info": "#0284C7",
        "outline": "#777587",
        "on-primary-container": "#dad7ff",
        "primary-fixed-dim": "#c3c0ff",
        "primary-hover": "#4338CA",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#bec6e0",
        "tertiary-container": "#006e4b",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#4edea3",
        "warning": "#F59E0B",
        "secondary": "#565e74",
        "success-soft": "#D1FAE5",
        "surface-container-high": "#dce9ff",
        "text-primary": "#0F172A",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-container": "#5c647a",
        "surface-container-highest": "#d3e4fe",
        "border-focus": "#6366F1",
        "primary": "#3525cd",
        "destructive": "#EF4444",
        "on-primary-fixed-variant": "#3323cc",
        "warning-soft": "#FEF3C7",
        "primary-soft": "#EEF2FF",
        "error-container": "#ffdad6",
        "on-surface-variant": "#464555",
        "border-neutral": "#E2E8F0",
        "surface": "#FFFFFF",
        "success": "#10B981",
        "surface-tint": "#4d44e3",
        "outline-variant": "#c7c4d8",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "#eff4ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-sm": "1rem",
        "margin-sm": "1rem",
        "space-xl": "2rem",
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        margin: "2rem",
        "space-xs": "0.25rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "price-display": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
