import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProductImages1790850000000 implements MigrationInterface {
  name = 'CreateProductImages1790850000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "product_image" (
        "product_image_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "product_id" integer NOT NULL,
        "image_url" varchar(2048) NOT NULL,
        "alt_text" varchar(200),
        "sort_order" integer NOT NULL DEFAULT 0,
        "is_primary" boolean NOT NULL DEFAULT false,
        CONSTRAINT "FK_product_image_product"
          FOREIGN KEY ("product_id") REFERENCES "product" ("product_id")
          ON DELETE CASCADE,
        CONSTRAINT "CHK_product_image_sort_order_nonnegative"
          CHECK ("sort_order" >= 0)
      )
    `);
    await queryRunner.query(
      'CREATE INDEX "IDX_product_image_product_sort" ON "product_image" ("product_id", "sort_order")',
    );
    await queryRunner.query(
      'CREATE UNIQUE INDEX "UQ_product_image_primary" ON "product_image" ("product_id") WHERE "is_primary" = true',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "UQ_product_image_primary"');
    await queryRunner.query('DROP INDEX "IDX_product_image_product_sort"');
    await queryRunner.query('DROP TABLE "product_image"');
  }
}
